version: '3'
services:
  movies-front:
    build:
      context: ./movies-front
      dockerfile: Dockerfile
    container_name: movies-front
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    environment:
      - REACT_PORT
      - REACT_APP_API_URI
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - movies-api
    command: npm start

  movies-api:
    build:
      context: ./movies-api
      dockerfile: Dockerfile
      target: build-release-stage
    container_name: movies-api 
    ports:
      - ${BIND_PORT}:${BIND_PORT}
    expose:
      - ${BIND_PORT}
    environment:
      - BIND_IP
      - BIND_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVER
      - POSTGRES_PORT
    depends_on: 
      db:
        condition: service_healthy
    command: /movies-api -b ${BIND_IP} -p ${BIND_PORT}

  db:
    image: postgres:15.3
    restart: always
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVER
      - POSTGRES_PORT
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    container_name: migration_flyway
    volumes:
      - ./sql_migrations:/flyway/sql
    command: ["-url=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}", "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}", "migrate"]
    depends_on:
      - db

volumes:
  db-data: